name: Docker

on:
  push:
    branches:
      - master
env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}:latest

jobs:
  push:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build image
        id: build
        uses: docker/build-push-action@v2.3.0
        with:
          tags: ${{ env.IMAGE_NAME }}
